name: signup_ui
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  lottie: ^0.7.0+1
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
   - family: Roboto
     fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

   - family: Merienda
     fonts:
        - asset: assets/fonts/Merienda-Regular.ttf
